/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.saswata;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import org.saswata.pdf.TextRun;
import org.saswata.pdf.TextRunStripper;

public class App {

  public static void main(String[] args) throws IOException {
    setupFlags();
    byte[] input = Files.readAllBytes(Paths.get(args[0]));
    System.out.println(input.length);
    List<List<TextRun>> pagedTextRuns = TextRunStripper.processPdf(input);
    List<AwsBillLineItem> lineItems = AwsBillParser.parseLineItems(pagedTextRuns);

    System.out.println(lineItems);
  }

  private static void setupFlags() {
    System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider");
    System.setProperty("org.apache.pdfbox.rendering.UsePureJavaCMYKConversion", "true");
  }
}
