/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pdfbox.sample;

import java.io.IOException;

public class App {

  public static void main(String[] args) throws IOException {
    setupFlags();
    //    byte[] input = Files.readAllBytes(Paths.get(args[0]));
    //    System.out.println(input.length);
    //    ColorTextStripper.processPdf(input);
    DrawPrintTextLocations.processPdf(args[0]);
  }

  private static void setupFlags() {
    System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider");
    System.setProperty("org.apache.pdfbox.rendering.UsePureJavaCMYKConversion", "true");
  }
}
