/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pdfbox.sample;

public class App {

  public static void main(String[] args) {
    setupFlags();
  }

  private static void setupFlags() {
    System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider");
    System.setProperty("org.apache.pdfbox.rendering.UsePureJavaCMYKConversion", "true");
  }
}
