/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pdfbox.sample;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class App {

  public static void main(String[] args) throws IOException {
    setupFlags();
    byte[] input = Files.readAllBytes(Paths.get(args[0]));
    System.out.println(input.length);
    ColorTextStripper.processPdf(input);
  }

  private static void setupFlags() {
    System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider");
    System.setProperty("org.apache.pdfbox.rendering.UsePureJavaCMYKConversion", "true");
  }
}
